
version: '3'

services:
  # rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq_host"
  #  environment:
  #    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #    RABBITMQ_DEFAULT_USER: "rabbitmq"
  #    RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #    RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  #  labels:
  #    NAME: "rabbitmq1"

  drenaj_server:
    build: .
    ports:
      - "9997:9997"
#    entrypoint: python -m drenaj_api.appstartup

  mongodb:
      image: 'bitnami/mongodb:latest'
      hostname: "mongodb_host"
      ports:
        - "27017:27017"
      volumes:
        - /home/onur/Desktop/projects/research/projects/interesting-half-projects/drenaj-mongodb-data:/bitnami

  web:
    image: nginx
    volumes:
     - ./host-configs/nginx/drenaj.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    command: /bin/bash -c "nginx -t && nginx -g 'daemon off;'"