# Turns out that these are not so important in general.
# They are only used in drenajinitdb.py which is not used
# now anyways.
project_root_dir: '/home/drenaj/code'
mongo_bin_dir: '/usr/bin'

mongo_host: 'localhost'
mongo_port: 27017

drenaj_app_environment: 'development'
drenaj_app_host: 'localhost'