project_root_dir: '/home/drenaj/drenaj/envs/staging'

mongo_bin_dir: '/usr/bin'
mongo_host: 'localhost'
mongo_port: 27017

drenaj_app_environment: 'development'
drenaj_app_host: 'integrator.cmpe.boun.edu.tr'

# Obtain these from Twitter, see project wiki
access_token_key: ""
access_token_secret: ""

auth_user_id: 'drenaj'
auth_password: 'tamtam'
