project_root_dir: '/home/direnaj/direnaj/envs/staging'

mongo_bin_dir: '/usr/bin'
mongo_host: 'localhost'
mongo_port: 27017

direnaj_app_environment: 'development'
direnaj_app_host: 'voltran.cmpe.boun.edu.tr'

# Obtain these from Twitter, see project wiki
access_token_key: ""
access_token_secret: ""

auth_user_id: 'direnaj'
auth_password: 'tamtam'
