project_root_dir: '/home/onur/Desktop/projects/research/projects/direnaj/repo'

mongo_bin_dir: '/usr/bin'
mongo_host: 'localhost'
mongo_port: 27017

direnaj_app_environment: 'development'
direnaj_app_host: 'localhost'

# Obtain these from Twitter, see project wiki
access_token_key: ""
access_token_secret: ""

auth_user_id: 'direnaj'
auth_password: 'tamtam'
