project_root_dir: '/home/drenaj/drenaj/envs/staging'

mongo_bin_dir: '/usr/bin'
mongo_host: 'localhost'
mongo_port: 27017

#mongo_port: 27017


# TODO: must change this to staging and host to drenaj-staging.cmpe.boun.edu.tr
drenaj_app_environment: 'staging'
drenaj_app_host: 'drenaj-staging.cmpe.boun.edu.tr'

drenaj_vis_environment: 'staging'
drenaj_vis_host: 'drenaj-staging.cmpe.boun.edu.tr'

# App related keys
app_consumer_key: 'SyyLuKNdeJ9lFeItE0Bg'
app_consumer_secret: 'eOqzcigVBydHqDTaQLP1fcQY7wFZXPZICIBuIgOnb4'

# Obtain these from Twitter, see project wiki
access_token_key: "788884670-zi7wAqsq0AINNY6kNTVRw78eXt3PzNtIaJJQE5Lj"
access_token_secret: "WNsG44DfKdbUEXwG5byFcskFcz2lZxvvYJtq59GM"

auth_user_id: 'drenaj'
auth_password: 'tamtam'
