project_root_dir: '/home/direnaj/direnaj/envs/staging'

mongo_bin_dir: '/usr/bin'
mongo_host: 'localhost'
mongo_port: 27017

direnaj_app_environment: 'development'
direnaj_app_host: 'voltran.cmpe.boun.edu.tr'

# direnaj_app_host_development: 80

# Obtain these from Twitter, see project wiki
access_token_key: "788884670-zi7wAqsq0AINNY6kNTVRw78eXt3PzNtIaJJQE5Lj"
access_token_secret: "WNsG44DfKdbUEXwG5byFcskFcz2lZxvvYJtq59GM"

auth_user_id: 'direnaj'
auth_password: 'tamtam'
