# Turns out that these are not so important in general.
# They are only used in direnajinitdb.py which is not used
# now anyways.
project_root_dir: '/home/direnaj/code'
mongo_bin_dir: '/usr/bin'

mongo_host: 'localhost'
mongo_port: 27017

direnaj_app_environment: 'development'
direnaj_app_host: 'localhost'